# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Laravel.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/php
image: php:7.4

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - vendor/
    - node_modules/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  # Update packages
  - apt-get update -yqq
    # Upgrade to Node 16
  - curl -sL https://deb.nodesource.com/setup_16.x | bash -
  # Install dependencies
  - apt-get install git libcurl4-gnutls-dev libicu-dev libmcrypt-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libpq-dev libonig-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libzip-dev gnupg rsync sshpass -yqq
  # Install php extensions
  - docker-php-ext-install mbstring curl json intl gd xml zip bz2 opcache
  # Install Composer and project dependencies.
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  # Copy over testing configuration.
  # Don't forget to set the database config in .env.testing correctly
  # DB_HOST=mysql
  # DB_DATABASE=project_name
  # DB_USERNAME=root
  # DB_PASSWORD=secret
  - cp .env.local .env
  # Run npm build
  # comment this out if you don't have a frontend build
  # you can change this to to your frontend building script like
  # Generate an application key. Re-cache.
  - php artisan key:generate
  # Install Node dependencies.
  # comment this out if you don't have a node dependency
  - npm install
  - npm run prod
  - export SSHPASS=$SSH_MARENGO_PSWD


deploy:
  script:
    # run deploy
    - rsync --recursive --links --owner --group --times --verbose --no-perms --chmod=D0644,F0644 --rsh="sshpass -e ssh -p $SSH_MARENGO_PORT -o StrictHostKeyChecking=no" --exclude '.git' --exclude '.gitlab-ci.yml' ./ $SSH_MARENGO_USER@$SSH_MARENGO_SERVER:/home/jg386444/new.marengo.ua
  only:
    - main

